### ISSUE TITLE
After last upgrade build are failed to run

### ISSUE THREAD

**Issue by bezzil85** [android-js/androidjs-sdk#11]
After upgrading with a help of `androidjs u`, any new build fails to get installed in emulator with next lines in log

> 2022-10-16 21:17:44.517 607-738/system_process W/AppIntegrityManagerServiceImpl: Exception reading file:///data/app/vmdl2069260508.tmp
    com.android.server.pm.PackageManagerException: /data/app/vmdl2069260508.tmp/base.apk (at Binary XML file line #9): com.android.js.webview.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
        at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:172)
        at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:150)
        at com.android.server.integrity.AppIntegrityManagerServiceImpl.getPackageArchiveInfo(AppIntegrityManagerServiceImpl.java:624)
        at com.android.server.integrity.AppIntegrityManagerServiceImpl.handleIntegrityVerification(AppIntegrityManagerServiceImpl.java:300)
        at com.android.server.integrity.AppIntegrityManagerServiceImpl.-$$Nest$mhandleIntegrityVerification(Unknown Source:0)
        at com.android.server.integrity.AppIntegrityManagerServiceImpl$1.lambda$onReceive$0$com-android-server-integrity-AppIntegrityManagerServiceImpl$1(AppIntegrityManagerServiceImpl.java:183)
        at com.android.server.integrity.AppIntegrityManagerServiceImpl$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Any help with downgrading to previous versions or fixing this issue is appreciated.

> androidjs -v
2.2.4

android-js sdk config
>{
	"version": "2.3.0"
}

**Comment by Chhekur** [comment]
Please update the androidjs-builder to latest one
```sh
npm install -g androidjs-builder@2.3.4
androidjs update
```

**Comment by bezzil85** [comment]
Sorry for late answer, i did pretty much same, by adding android:exported=true in cached AndroidManifest.xml file, guess it could be closed
